name: qbicc Continuous Integration
on:
  schedule:
    - cron: '17 1 * * *'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.adoc'
    branches: [ main ]
    types: [ opened, synchronize, reopened ]
jobs:
  build-matrix:
    name: "Matrix build"
    strategy:
      fail-fast: false
      matrix:
        llvm-version: ["15", "16", "17"]
#        os: [ubuntu-latest, macos-latest-xlarge]
        os: [macos-latest-xlarge]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1.9.0
        with:
          version: ${{ matrix.llvm-version }}
          directory: ${{ runner.temp }}/llvm-install

      - name: Install `libgcc` (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libgcc-11-dev

      - name: Install libunwind (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get install -y libunwind-dev

      - name: Install OpenJDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Clone qbicc
        uses: actions/checkout@v4
        with:
          path: qbicc-${{ matrix.os }}-llvm${{ matrix.llvm-version }}

      - name: Install qbicc (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
            LIBRARY_PATH: /usr/lib/gcc/x86_64-linux-gnu/11:/usr/lib/x86_64-linux-gnu
            CC: clang
        run: |
          ulimit -c 819200 # 400mb
          ./ci/prepare_for_core_linux.sh
          mvn --batch-mode install
        working-directory: ./qbicc-${{ matrix.os }}-llvm${{ matrix.llvm-version }}

      - name: Install qbicc (Mac OS)
        if: matrix.os == 'macos-latest-xlarge'
        env:
            LIBRARY_PATH: $(brew --prefix gcc)/lib/gcc/11
            CC: gcc
        run: |
          ulimit -c 819200 # 400mb
          ./ci/prepare_for_core_macos.sh
          mvn --batch-mode install
        working-directory: ./qbicc-${{ matrix.os }}-llvm${{ matrix.llvm-version }}

      - name: Prepare failure archive (if maven failed)
        if: failure()
        shell: bash
        run: find . -type d -name '*-reports' -o -name "*-logs" | tar -czf test-reports.tgz -T -

      - name: Upload failure Archive (if maven failed)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-reports
          path: |
            'test-reports.tgz'
            ./qbicc-*/core/*
            ./qbicc-*/integration-tests/target/native/qbicc-integration-tests
